### ISSUE TITLE
api: Opprett Prosjekt kontroller

### ISSUE THREAD

**Issue by Fr3dric0** [Fr3dric0/chriba2#13]
Skal handtere følgande ruter

- [ ] GET `/projects` - Get all projects
- [ ] GET `/projects/:project` - Get specific project
- [ ] POST `/projects` - Create project
- [ ] PUT `/projects/:project` - Update project
- [ ] POST `/projects/:project/img/:size` - Last opp bilde
- [ ] DELETE `/projects/:project/img/:size` - Fjern bilde
- [ ] GET `/projects/:project` - Slett prosjekt

**Comment by Fr3dric0** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Opprett Prosjekt kontroller](https://trello.com/c/fbm0JyGV/1-opprett-prosjekt-kontroller)

**Comment by hehug7** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Opprett Prosjekt kontroller](https://trello.com/c/fbm0JyGV/1-opprett-prosjekt-kontroller)
