### ISSUE TITLE
Implementerer Dashboard

### ISSUE THREAD

**Issue by hehug7** [Fr3dric0/chriba2#19]
Dashboard med implementering av karusell.

**Comment by Fr3dric0** [comment]
Er veeeldig generell issue dette her. Kanskje gje den et nytt namn? 🇮🇴

**Comment by Fr3dric0** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementer Dashboard](https://trello.com/c/012uBWHW/10-implementer-dashboard)
