### ISSUE TITLE
Komponent: Header

### ISSUE THREAD

**Issue by Fr3dric0** [Fr3dric0/chriba2#6]
Header er nødt til å byggast opp igjen, og noken må ta ansvar for dette.

Fallgruver her, kan vere om header er nødt til å lytte på informasjon frå elementet over, eller sende ut oppdateringar. 

> Eksempel kan vere, om det skulle vore ein `login` eller `logout` knapp i headaren.
> Er det då header som skal vere ansvarlig for å logge ut brukaren, eller skal den bere sende beskjed opp til 
> komponenten over om at han vil logge ut?
(_Er ikkje sikkert dette kjem til å bli eit problem i det heiletatt, men lurt å ha i tankane_)

**Comment by dliso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementer header](https://trello.com/c/EgYq1WTk/8-implementer-header)
